### ISSUE TITLE
Option to specify a how the PDF should be generated. E.g. using custom section labels

### ISSUE THREAD

**Issue by sinaru** [sinaru/cv-builder#8]
Suppose we want to have custom labels. E.g. Instead "Work Experience", we want to say "Employment History" . So we need to define a structure for these cases. And feed it into the generator so the template can use it instead of a default title.

```yaml
# meta_def.yaml
  experiences: 
    label: Employment History
```
